steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/sustained-works-450506-q5/my-app:$SHORT_SHA'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image'
  args:
  - 'push'
  - 'gcr.io/sustained-works-450506-q5/my-app:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Get Cluster Credentials'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1 --project sustained-works-450506-q5

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Deploy to GKE'
  env:
  - 'KUBECONFIG=/workspace/.kube/config'
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'  # Replace with your cluster's region
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'  # Replace with your cluster's zone
  - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'  # Replace with your cluster's name
  args:
  - 'set'
  - 'image'
  - 'deployment/my-app-deployment'
  - 'my-app=gcr.io/sustained-works-450506-q5/my-app:$SHORT_SHA'
  - '--namespace=default'

images:
- 'gcr.io/sustained-works-450506-q5/my-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
